package prov

import (
	"log"
	"time"
)

func provision2012(targetHost string) error {
	year := 2012

	prov := NewProvisioner(targetHost)

	prov.CreateTour(year)

	prov.CreateEtappe(year, 1, date(year, time.June, 30), "Liège", "Liège", 6, TimeTrial)
	prov.CreateEtappe(year, 2, date(year, time.July, 1), "Liège", "Seraing", 198, Flat)
	prov.CreateEtappe(year, 3, date(year, time.July, 2), "Visé", "Tournai", 207, Flat)
	prov.CreateEtappe(year, 4, date(year, time.July, 3), "Orchies", "Boulogne-sur-Mer", 200, Hilly)
	prov.CreateEtappe(year, 5, date(year, time.July, 4), "Abbeville", "Rouen", 214, Flat)
	prov.CreateEtappe(year, 6, date(year, time.July, 5), "Rouen", "Saint-Quentin", 196, Flat)
	prov.CreateEtappe(year, 7, date(year, time.July, 6), "Épernay", "Metz", 207, Flat)
	prov.CreateEtappe(year, 8, date(year, time.July, 7), "Tomblaine", "La Planche des Belles Filles", 199, Hilly)
	prov.CreateEtappe(year, 9, date(year, time.July, 8), "Belfort", "Porrentruy", 157, Hilly)
	prov.CreateEtappe(year, 10, date(year, time.July, 9), "Arc-et-Senans", "Besançon", 41, TimeTrial)
	prov.CreateEtappe(year, 11, date(year, time.July, 11), "Mâcon", "Bellegarde-sur-Valserine", 194, Mountains)
	prov.CreateEtappe(year, 12, date(year, time.July, 12), "Albertville", "La Toussuire - Les Sybelles", 148, Mountains)
	prov.CreateEtappe(year, 13, date(year, time.July, 13), "Saint-Jean-de-Maurienne", "Annonay Davézieux", 226, Hilly)
	prov.CreateEtappe(year, 14, date(year, time.July, 14), "Saint-Paul-Trois-Châteaux", "Le Cap d’Agde", 217, Flat)
	prov.CreateEtappe(year, 15, date(year, time.July, 15), "Limoux", "Foix", 191, Mountains)
	prov.CreateEtappe(year, 16, date(year, time.July, 16), "Samatan", "Pau", 158, Flat)
	prov.CreateEtappe(year, 17, date(year, time.July, 18), "Pau", "Bagnères-de-Luchon", 197, Mountains)
	prov.CreateEtappe(year, 18, date(year, time.July, 19), "Bagnères-de-Luchon", "Peyragudes", 143, 1)
	prov.CreateEtappe(year, 19, date(year, time.July, 20), "Blagnac", "Brive-la-Gaillarde", 222, Mountains)
	prov.CreateEtappe(year, 20, date(year, time.July, 21), "Bonneval", "Chartres", 53, TimeTrial)
	prov.CreateEtappe(year, 21, date(year, time.July, 22), "Rambouillet", "Paris Champs-Élysées", 120, Flat)

	prov.CreateCyclist(year, 9, "VAN GARDEREN Tejay", "BMC")
	prov.CreateCyclist(year, 8, "SCH€R Michael", "BMC")
	prov.CreateCyclist(year, 7, "QUINZIATO Manuel", "BMC")
	prov.CreateCyclist(year, 6, "MOINARD Ama‘l", "BMC")
	prov.CreateCyclist(year, 5, "HINCAPIE George", "BMC")
	prov.CreateCyclist(year, 4, "GILBERT Philippe", "BMC")
	prov.CreateCyclist(year, 3, "CUMMINGS Stephen", "BMC")
	prov.CreateCyclist(year, 2, "BURGHARDT Marcus", "BMC")
	prov.CreateCyclist(year, 1, "EVANS Cadel", "BMC")

	prov.CreateCyclist(year, 19, "ZUBELDIA Haimar", "RNT")
	prov.CreateCyclist(year, 18, "VOIGT Jens", "RNT")
	prov.CreateCyclist(year, 17, "POPOVYCH Yaroslav", "RNT")
	prov.CreateCyclist(year, 16, "MONFORT Maxime", "RNT")
	prov.CreateCyclist(year, 15, "KL…DEN AndrŽas", "RNT")
	prov.CreateCyclist(year, 14, "HORNER Christopher", "RNT")
	prov.CreateCyclist(year, 13, "GALLOPIN Tony", "RNT")
	prov.CreateCyclist(year, 12, "CANCELLARA Fabian", "RNT")
	prov.CreateCyclist(year, 11, "SCHLECK Frank", "RNT")

	prov.CreateCyclist(year, 29, "ROLLAND Pierre", "EUC")
	prov.CreateCyclist(year, 28, "MALACARNE Davide", "EUC")
	prov.CreateCyclist(year, 27, "KERN Christophe", "EUC")
	prov.CreateCyclist(year, 26, "JEROME Vincent", "EUC")
	prov.CreateCyclist(year, 25, "GENE Yohann", "EUC")
	prov.CreateCyclist(year, 24, "GAUTIER Cyril", "EUC")
	prov.CreateCyclist(year, 23, "BERNAUDEAU Giovanni", "EUC")
	prov.CreateCyclist(year, 22, "ARASHIRO Yukiya", "EUC")
	prov.CreateCyclist(year, 21, "VOECKLER Thomas", "EUC")

	prov.CreateCyclist(year, 39, "VERDUGO Gorka", "EUS")
	prov.CreateCyclist(year, 38, "URTASUN PEREZ Pablo", "EUS")
	prov.CreateCyclist(year, 37, "TXURRUKA Amets", "EUS")
	prov.CreateCyclist(year, 36, "PEREZ MORENO Ruben", "EUS")
	prov.CreateCyclist(year, 35, "MARTINEZ Egoi", "EUS")
	prov.CreateCyclist(year, 34, "IZAGUIRRE INSAUSTI Gorka", "EUS")
	prov.CreateCyclist(year, 32, "ASTARLOZA Mikel", "EUS")
	prov.CreateCyclist(year, 31, "SANCHEZ Samuel", "EUS")

	prov.CreateCyclist(year, 49, "VIGANO Davide", "LAM")
	prov.CreateCyclist(year, 48, "STORTONI Simone", "LAM")
	prov.CreateCyclist(year, 47, "PETACCHI Alessandro", "LAM")
	prov.CreateCyclist(year, 46, "MARZANO Marco", "LAM")
	prov.CreateCyclist(year, 45, "LLOYD Matthew", "LAM")
	prov.CreateCyclist(year, 43, "HONDO Danilo", "LAM")
	prov.CreateCyclist(year, 42, "BOLE Grega", "LAM")
	prov.CreateCyclist(year, 41, "SCARPONI Michele", "LAM")

	prov.CreateCyclist(year, 59, "VANOTTI Alessandro", "LIQ")
	prov.CreateCyclist(year, 58, "SZMYD Sylvester", "LIQ")
	prov.CreateCyclist(year, 57, "SAGAN Peter", "LIQ")
	prov.CreateCyclist(year, 56, "OSS Daniel", "LIQ")
	prov.CreateCyclist(year, 55, "NERZ Dominik", "LIQ")
	prov.CreateCyclist(year, 54, "KOREN Kristijan", "LIQ")
	prov.CreateCyclist(year, 53, "CANUTI Federico", "LIQ")
	prov.CreateCyclist(year, 52, "BASSO Ivan", "LIQ")
	prov.CreateCyclist(year, 51, "NIBALI Vincenzo", "LIQ")

	prov.CreateCyclist(year, 69, "ZABRISKIE David", "GRS")
	prov.CreateCyclist(year, 68, "VANDE VELDE Christian", "GRS")
	prov.CreateCyclist(year, 67, "VAN SUMMEREN Johan", "GRS")
	prov.CreateCyclist(year, 66, "MILLAR David", "GRS")
	prov.CreateCyclist(year, 65, "MARTIN Daniel", "GRS")
	prov.CreateCyclist(year, 64, "HUNTER Robert", "GRS")
	prov.CreateCyclist(year, 63, "FARRAR Tyler", "GRS")
	prov.CreateCyclist(year, 62, "DANIELSON Thomas", "GRS")
	prov.CreateCyclist(year, 61, "HESJEDAL Ryder", "GRS")

	prov.CreateCyclist(year, 79, "ROCHE Nicolas", "ALM")
	prov.CreateCyclist(year, 78, "RIBLON Christophe", "ALM")
	prov.CreateCyclist(year, 77, "MINARD SŽbastien", "ALM")
	prov.CreateCyclist(year, 76, "KADRI Blel", "ALM")
	prov.CreateCyclist(year, 75, "HINAULT SŽbastien", "ALM")
	prov.CreateCyclist(year, 74, "DUPONT Hubert", "ALM")
	prov.CreateCyclist(year, 73, "CHEREL Mikael", "ALM")
	prov.CreateCyclist(year, 72, "BOUET Maxime", "ALM")
	prov.CreateCyclist(year, 71, "PERAUD Jean-Christophe", "ALM")

	prov.CreateCyclist(year, 89, "ZINGLE Romain", "COF")
	prov.CreateCyclist(year, 88, "MONCOUTIE David", "COF")
	prov.CreateCyclist(year, 87, "MATE MARDONES Luis Angel", "COF")
	prov.CreateCyclist(year, 86, "GHYSELINCK Jan", "COF")
	prov.CreateCyclist(year, 85, "FOUCHARD Julien", "COF")
	prov.CreateCyclist(year, 84, "EDET Nicolas", "COF")
	prov.CreateCyclist(year, 83, "DUMOULIN Samuel", "COF")
	prov.CreateCyclist(year, 82, "DI GREGORIO RŽmy", "COF")
	prov.CreateCyclist(year, 81, "TAARAMAE Rein", "COF")

	prov.CreateCyclist(year, 99, "SIMON Julien", "SAU")
	prov.CreateCyclist(year, 98, "MARINO Jean Marc", "SAU")
	prov.CreateCyclist(year, 97, "LEVARLET Guillaume", "SAU")
	prov.CreateCyclist(year, 96, "LEMOINE Cyril", "SAU")
	prov.CreateCyclist(year, 95, "JEANDESBOZ Fabrice", "SAU")
	prov.CreateCyclist(year, 94, "FEILLU Brice", "SAU")
	prov.CreateCyclist(year, 93, "ENGOULVENT Jimmy", "SAU")
	prov.CreateCyclist(year, 92, "DELAPLACE Anthony", "SAU")
	prov.CreateCyclist(year, 91, "COPPEL JŽr™me", "SAU")

	prov.CreateCyclist(year, 109, "SIVTSOV Kanstantsin", "SKY")
	prov.CreateCyclist(year, 108, "ROGERS Michael", "SKY")
	prov.CreateCyclist(year, 107, "PORTE Richie", "SKY")
	prov.CreateCyclist(year, 106, "KNEES Christian", "SKY")
	prov.CreateCyclist(year, 105, "FROOME Christopher", "SKY")
	prov.CreateCyclist(year, 104, "EISEL Bernhard", "SKY")
	prov.CreateCyclist(year, 103, "CAVENDISH Mark", "SKY")
	prov.CreateCyclist(year, 102, "BOASSON HAGEN Edvald", "SKY")
	prov.CreateCyclist(year, 101, "WIGGINS Bradley", "SKY")

	prov.CreateCyclist(year, 119, "VANENDERT Jelle", "LTB")
	prov.CreateCyclist(year, 118, "SIEBERG Marcel", "LTB")
	prov.CreateCyclist(year, 117, "ROELANDTS Jurgen", "LTB")
	prov.CreateCyclist(year, 116, "HENDERSON Gregory", "LTB")
	prov.CreateCyclist(year, 115, "HANSEN Adam", "LTB")
	prov.CreateCyclist(year, 114, "GREIPEL AndrŽ", "LTB")
	prov.CreateCyclist(year, 113, "DE GREEF Francis", "LTB")
	prov.CreateCyclist(year, 112, "BAK Lars", "LTB")
	prov.CreateCyclist(year, 111, "VAN DEN BROECK Jurgen", "LTB")

	prov.CreateCyclist(year, 129, "VAN HUMMEL Kenny Robert", "VCD")
	prov.CreateCyclist(year, 128, "VALLS FERRI Rafael", "VCD")
	prov.CreateCyclist(year, 127, "RUIJGH Rob", "VCD")
	prov.CreateCyclist(year, 126, "POELS Wouter", "VCD")
	prov.CreateCyclist(year, 125, "MARCATO Marco", "VCD")
	prov.CreateCyclist(year, 124, "LARSSON Gustav", "VCD")
	prov.CreateCyclist(year, 123, "HOOGERLAND Johnny", "VCD")
	prov.CreateCyclist(year, 122, "BOECKMANS Kris", "VCD")
	prov.CreateCyclist(year, 121, "WESTRA Lieuwe", "VCD")

	prov.CreateCyclist(year, 139, "VORGANOV Eduard", "KAT")
	prov.CreateCyclist(year, 138, "TROFIMOV Yury", "KAT")
	prov.CreateCyclist(year, 137, "PAOLINI Luca", "KAT")
	prov.CreateCyclist(year, 136, "KUCHYNSKI Aliaksandr", "KAT")
	prov.CreateCyclist(year, 135, "HORRACH Joan", "KAT")
	prov.CreateCyclist(year, 134, "GUSEV Vladimir", "KAT")
	prov.CreateCyclist(year, 133, "FREIRE Oscar", "KAT")
	prov.CreateCyclist(year, 132, "CARUSO Gianpaolo", "KAT")
	prov.CreateCyclist(year, 131, "MENCHOV Denis", "KAT")

	prov.CreateCyclist(year, 149, "VICHOT Arthur", "FDJ")
	prov.CreateCyclist(year, 148, "ROY JŽrŽmy", "FDJ")
	prov.CreateCyclist(year, 147, "ROUX Anthony", "FDJ")
	prov.CreateCyclist(year, 146, "PINOT Thibaut", "FDJ")
	prov.CreateCyclist(year, 145, "PINEAU Cedric", "FDJ")
	prov.CreateCyclist(year, 144, "LADAGNOUS Matthieu", "FDJ")
	prov.CreateCyclist(year, 143, "HUTAROVICH Yauheni", "FDJ")
	prov.CreateCyclist(year, 142, "FEDRIGO Pierrick", "FDJ")
	prov.CreateCyclist(year, 141, "CASAR Sandy", "FDJ")

	prov.CreateCyclist(year, 159, "WYNANTS Maarten", "RAB")
	prov.CreateCyclist(year, 158, "TJALLINGII Maarten", "RAB")
	prov.CreateCyclist(year, 157, "TEN DAM Laurens", "RAB")
	prov.CreateCyclist(year, 156, "TANKINK Bram", "RAB")
	prov.CreateCyclist(year, 155, "SANCHEZ Luis-Leon", "RAB")
	prov.CreateCyclist(year, 154, "RENSHAW Mark", "RAB")
	prov.CreateCyclist(year, 153, "MOLLEMA Bauke", "RAB")
	prov.CreateCyclist(year, 152, "KRUIJSWIJK Steven", "RAB")
	prov.CreateCyclist(year, 151, "GESINK Robert", "RAB")

	prov.CreateCyclist(year, 169, "ROJAS Jose Joaquin", "MOV")
	prov.CreateCyclist(year, 168, "PLAZA MOLINA Ruben", "MOV")
	prov.CreateCyclist(year, 167, "KIRYIENKA Vasili", "MOV")
	prov.CreateCyclist(year, 166, "KARPETS Vladimir", "MOV")
	prov.CreateCyclist(year, 165, "GUTIERREZ JosŽ Ivan", "MOV")
	prov.CreateCyclist(year, 164, "ERVITI Imanol", "MOV")
	prov.CreateCyclist(year, 163, "COSTA Rui Alberto", "MOV")
	prov.CreateCyclist(year, 162, "COBO ACEBO Juan Jose", "MOV")
	prov.CreateCyclist(year, 161, "VALVERDE Alejandro", "MOV")

	prov.CreateCyclist(year, 179, "SORENSEN Nicki", "STB")
	prov.CreateCyclist(year, 178, "SORENSEN Chris Anker", "STB")
	prov.CreateCyclist(year, 176, "NUYENS Nick", "STB")
	prov.CreateCyclist(year, 175, "MORKOV Michael", "STB")
	prov.CreateCyclist(year, 174, "LUND Anders", "STB")
	prov.CreateCyclist(year, 173, "KROON Karsten", "STB")
	prov.CreateCyclist(year, 172, "HAEDO Juan Jose", "STB")

	prov.CreateCyclist(year, 189, "VINOKOUROV Alexandre", "AST")
	prov.CreateCyclist(year, 188, "KISERLOVSKI Robert", "AST")
	prov.CreateCyclist(year, 187, "KESSIAKOFF Fredrik", "AST")
	prov.CreateCyclist(year, 186, "KASHECHKIN Andrey", "AST")
	prov.CreateCyclist(year, 185, "IGLINSKIY Maxim", "AST")
	prov.CreateCyclist(year, 184, "GRIVKO Andriy", "AST")
	prov.CreateCyclist(year, 183, "FOFONOV Dmitriy", "AST")
	prov.CreateCyclist(year, 182, "BOZIC Borut", "AST")
	prov.CreateCyclist(year, 181, "BRAJKOVIC Janez", "AST")

	prov.CreateCyclist(year, 199, "VELITS Peter", "OPQ")
	prov.CreateCyclist(year, 198, "VELITS Martin", "OPQ")
	prov.CreateCyclist(year, 197, "PINEAU JŽr™me", "OPQ")
	prov.CreateCyclist(year, 196, "MARTIN Tony", "OPQ")
	prov.CreateCyclist(year, 195, "GRABSCH Bert", "OPQ")
	prov.CreateCyclist(year, 194, "DEVENYNS Dries", "OPQ")
	prov.CreateCyclist(year, 193, "DE WEERT Kevin", "OPQ")
	prov.CreateCyclist(year, 192, "CHAVANEL Sylvain", "OPQ")
	prov.CreateCyclist(year, 191, "LEIPHEIMER Levi", "OPQ")

	prov.CreateCyclist(year, 209, "WEENING Pieter", "OGE")
	prov.CreateCyclist(year, 208, "OÕGRADY Stuart", "OGE")
	prov.CreateCyclist(year, 207, "LANGEVELD Sebastian", "OGE")
	prov.CreateCyclist(year, 206, "LANCASTER Brett Daniel", "OGE")
	prov.CreateCyclist(year, 205, "IMPEY Daryl", "OGE")
	prov.CreateCyclist(year, 204, "GOSS Matthew Harley", "OGE")
	prov.CreateCyclist(year, 203, "COOKE Baden", "OGE")
	prov.CreateCyclist(year, 202, "ALBASINI Michael", "OGE")
	prov.CreateCyclist(year, 201, "GERRANS Simon", "OGE")

	prov.CreateCyclist(year, 219, "VEELERS Tom", "ARG")
	prov.CreateCyclist(year, 218, "TIMMER Albert", "ARG")
	prov.CreateCyclist(year, 217, "SPRICK Matthieu", "ARG")
	prov.CreateCyclist(year, 216, "HUGUET Yann", "ARG")
	prov.CreateCyclist(year, 215, "GRETSCH Patrick", "ARG")
	prov.CreateCyclist(year, 214, "FR…HLINGER Johannes", "ARG")
	prov.CreateCyclist(year, 213, "DE KORT Koen", "ARG")
	prov.CreateCyclist(year, 212, "CURVERS Roy", "ARG")
	prov.CreateCyclist(year, 211, "KITTEL Marcel", "ARG")

	prov.CreateGambler("mgrol", "Marc Grol", "marc.grol@gmail.com")

	prov.CreateGamblerTeam(year, "mgrol", []int{1, 2, 3, 4, 5, 6, 7, 8, 9})

	if prov.err != nil {
		log.Printf("Error provisioning %s", prov.err)
		return prov.err
	}
	return nil
}
