// Generated by: gen
// TypeWriter: stringer
// Directive: +gen on EtappeKind

package tour

import (
	"fmt"
)

const _EtappeKind_name = "FlatHillyMountainsTimeTrial"

var _EtappeKind_index = [...]uint8{0, 4, 9, 18, 27}

func (i EtappeKind) String() string {
	i -= 1
	if i < 0 || i+1 >= EtappeKind(len(_EtappeKind_index)) {
		return fmt.Sprintf("EtappeKind(%d)", i+1)
	}
	return _EtappeKind_name[_EtappeKind_index[i]:_EtappeKind_index[i+1]]
}
